Koala\ContentBundle\Entity\Page:
    type: entity
    table: pages
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        title:
            type: string
            length: 100
        layout:
            type: string
    oneToMany:
        regions:
            targetEntity: Koala\ContentBundle\Entity\Region
            mappedBy: page
            cascade: [remove]
        menuItems:
            targetEntity: Koala\ContentBundle\Entity\MenuItem
            mappedBy: page
            cascade: [remove]
        routes:
            targetEntity: Koala\ContentBundle\Entity\Route
            mappedBy: page
            cascade: [remove, persist]
