Koala\ContentBundle\Entity\Page:
    type: entity
    table: pages
    repositoryClass: Gedmo\Tree\Entity\Repository\NestedTreeRepository
    gedmo:
        tree:
            type: nested
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        lft:
            type: integer
            gedmo: [treeLeft]
        lvl:
            type: integer
            gedmo: [treeLevel]
        rgt:
            type: integer
            gedmo: [treeRight]
        root:
            type: integer
            nullable: true
            gedmo: [treeRoot]
        menuTitle:
            type: string
            length: 100
        slug:
            type: string
            length: 128
            unique: true
            gedmo:
                slug:
                    fields: [menuTitle]
        url:
            type: string
            length: 128
            unique: true
            nullable: true
        layout:
            type: string
    oneToMany:
        children:
            targetEntity: Koala\ContentBundle\Entity\Page
            mappedBy: parent
            orderBy: {lft: ASC}
        regions:
            targetEntity: Koala\ContentBundle\Entity\Region
            mappedBy: page
            cascade: [remove]
    manyToOne:
        parent:
            targetEntity: Koala\ContentBundle\Entity\Page
            inversedBy: children
            joinColumn:
                name: parent_id
                referencedColumnName: id
                onDelete: SET NULL
            gedmo:
                - treeParent
