Koala\ContentBundle\Entity\Page:
    type: entity
    table: pages
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        title:
            type: string
            length: 100
        slug:
            type: string
            length: 128
            unique: true
            gedmo:
                slug:
                    fields: [title]
        url:
            type: string
            length: 128
            unique: true
            nullable: true
        layout:
            type: string
    oneToMany:
        regions:
            targetEntity: Koala\ContentBundle\Entity\Region
            mappedBy: page
            cascade: [remove]
        menuItems:
            targetEntity: Koala\ContentBundle\Entity\MenuItem
            mappedBy: page
            cascade: [remove]