Koala\ContentBundle\Entity\Route:
    type: entity
    table: routes
    lifecycleCallbacks:
        postLoad: [ init ]
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        pattern:
            type: string
            length: 100
    manyToOne:
        page:
            targetEntity: Koala\ContentBundle\Entity\Page
            inversedBy: routes
            cascade: [persist]
