parameters:
    layouts_form_type.class: Koala\ContentBundle\Type\LayoutsFormType
    layouts_provider.class: Koala\ContentBundle\LayoutsProvider
    layouts_provider.layouts:
        default: {name: Default Layout, template: 'KoalaContentBundle:Layouts:default.html.twig'}
    mercury_twig_extension.class: Koala\ContentBundle\Twig\MercuryExtension
    mercury_twig_extension.template: 'KoalaContentBundle::mercury_region.html.twig'
    mercury_twig_extension.defaults: {tag: 'div', default: ''}

services:
    layouts_provider:
        class: %layouts_provider.class%
        arguments:
            - %layouts_provider.layouts%
    layouts_form_type:
        class: %layouts_form_type.class%
        arguments:
            - @layouts_provider
        tags:
            - { name: form.type, alias: layouts }
    mercury_twig_extension:
        class: %mercury_twig_extension.class%
        arguments:
            - %mercury_twig_extension.template%
            - %mercury_twig_extension.defaults%
        tags:
            - { name: twig.extension }
