parameters:
    layouts_form_type.class: Koala\ContentBundle\Type\LayoutsFormType
    layouts_provider.class: Koala\ContentBundle\LayoutsProvider
    layouts_provider.layouts:

services:
    layouts_provider:
        class: %layouts_provider.class%
        arguments:
            - %layouts_provider.layouts%
    layouts_form_type:
        class: %layouts_form_type.class%
        arguments:
            - @layouts_provider
        tags:
            - { name: form.type, alias: layouts }