parameters:
    layouts_form_type.class: Koala\ContentBundle\Type\LayoutsFormType
    layouts_provider.class: Koala\ContentBundle\LayoutsProvider
    layouts_provider.layouts:
        default: {name: Default Layout, template: 'KoalaContentBundle:Layouts:default.html.twig'}
    mercury_twig_extension.class: Koala\ContentBundle\Twig\MercuryExtension
    mercury_twig_extension.template: 'KoalaContentBundle::mercury_region.html.twig'
    mercury_twig_extension.defaults: {tag: 'div', default: ''}
    mercury_twig_extension.package:
        javascripts:
            - mercury/javascripts/mercury.min.js
            - mercury/javascripts/mercury_dialogs.js
            - bundles/koalacontent/js/mercury_plugin.js
        stylesheets:
            - mercury/stylesheets/mercury.bundle.css
            - bundles/koalacontent/css/mercury_plugin.css
    menu_provider.class: Koala\ContentBundle\Service\EntityMenuProvider
    menu_provider.entity: 'KoalaContentBundle:MenuItem'

    route_repository.class: Koala\ContentBundle\Entity\RouteRepository
    route_repository.entity: 'KoalaContentBundle:Route'
    dynamic_router.class: Symfony\Cmf\Bundle\RoutingExtraBundle\Routing\DynamicRouter
    mapper_page_controller.class: Symfony\Cmf\Component\Routing\Mapper\ControllerClassMapper

services:
    layouts_provider:
        class: %layouts_provider.class%
        arguments:
            - %layouts_provider.layouts%
    layouts_form_type:
        class: %layouts_form_type.class%
        arguments:
            - @layouts_provider
        tags:
            - { name: form.type, alias: layouts }
    mercury_twig_extension:
        class: %mercury_twig_extension.class%
        arguments:
            - %mercury_twig_extension.template%
            - %mercury_twig_extension.defaults%
            - %mercury_twig_extension.package%
        tags:
            - { name: twig.extension }
    menu_provider:
        class: %menu_provider.class%
        arguments:
            - @service_container
            - @knp_menu.factory
            - @doctrine.orm.default_entity_manager
            - %menu_provider.entity%
        tags:
            - { name: knp_menu.provider }
    koala_content.route_repository:
        class: %route_repository.class%
        arguments:
            - @doctrine.orm.default_entity_manager
            - %route_repository.entity%
    koala_content.mapper_page_controller:
        class: %mapper_page_controller.class%
        arguments:
            - Koala\ContentBundle\Entity\Page: KoalaContentBundle:Page:show
    koala_content.dynamic_router:
        class: %dynamic_router.class%
        arguments:
            - @koala_content.route_repository
        calls:
            - [ setContext, [@router.request_context]]
            - [ setContainer, [@service_container]]
            - [ addControllerMapper, [@koala_content.mapper_page_controller]]