Koala\ContentBundle\Entity\Page:
    properties:
        menuTitle:
            - NotBlank: ~
        url:
            - NotBlank: ~
        layout:
            - NotBlank: ~

Koala\ContentBundle\Entity\Region:
    properties:
        name:
            - NotBlank: ~
        content:
            - NotBlank: ~
