Koala\ContentBundle\Entity\Page:
    properties:
        menuTitle:
            - NotBlank: ~

Koala\ContentBundle\Entity\Region:
    properties:
        name:
            - NotBlank: ~
        content:
            - NotBlank: ~
