Koala\ContentBundle\Entity\MenuItem:
    properties:
        label:
            - NotBlank: ~

Koala\ContentBundle\Entity\Page:
    properties:
        title:
            - NotBlank: ~
        slug:
            - NotBlank: ~
        url:
            - NotBlank: ~
        layout:
            - NotBlank: ~

Koala\ContentBundle\Entity\Region:
    properties:
        name:
            - NotBlank: ~
        content:
            - NotBlank: ~
